defmodule DragNStampWeb.SEOHelpers do
  @moduledoc """
  Helper functions for SEO optimization and canonical URL management.
  """

  @doc """
  Returns the canonical domain for the application.
  In production, this should be stamp-bot.com
  """
  def canonical_domain do
    case Application.get_env(:drag_n_stamp, DragNStampWeb.Endpoint)[:url][:host] do
      nil -> "stamp-bot.com"
      host when host in ["localhost", "127.0.0.1"] -> "stamp-bot.com"
      host -> host
    end
  end

  @doc """
  Generates a canonical URL for a given path.
  """
  def canonical_url(path \\ "/") do
    "https://#{canonical_domain()}#{path}"
  end

  @doc """
  Generates SEO-optimized meta description based on page content.
  """
  def meta_description(type, opts \\ [])

  def meta_description(:home, _opts) do
    "Generate precise YouTube video timestamps automatically using AI. Create chapter markers, find key moments, and improve video accessibility with StampBot's intelligent timestamp generation."
  end

  def meta_description(:feed, _opts) do
    "Browse the latest YouTube video timestamps generated by our AI. Find chapter markers and key moments from videos across all channels, updated in real-time."
  end

  def meta_description(:leaderboard, _opts) do
    "Discover the most active YouTube timestamp contributors and popular channels. See who's creating the most AI-generated video chapters and top performing content."
  end

  def meta_description(:more_info, _opts) do
    "Learn how to use StampBot's AI-powered YouTube timestamp generator. Get the bookmarklet, API documentation, and tips for creating better video chapters."
  end

  def meta_description(:extension, _opts) do
    "Install the StampBot browser extension for one-click YouTube timestamp generation. Automatically create video chapters while browsing YouTube."
  end

  def meta_description(_, _opts) do
    "StampBot - AI-powered YouTube timestamp generator for creating video chapters and finding key moments automatically."
  end

  @doc """
  Generates page-specific title with SEO optimization.
  """
  def page_title(type, opts \\ [])

  def page_title(:home, _opts) do
    "StampBot - AI YouTube Timestamp Generator | Create Video Chapters Instantly"
  end

  def page_title(:feed, _opts) do
    "YouTube Timestamp Feed | Recently Created Video Chapters"
  end

  def page_title(:leaderboard, _opts) do
    "Timestamp Leaderboard | Top YouTube Content Creators & Contributors"
  end

  def page_title(:more_info, _opts) do
    "How to Use StampBot | YouTube Timestamp Generator Guide & API"
  end

  def page_title(:extension, _opts) do
    "StampBot Browser Extension | One-Click YouTube Timestamp Generation"
  end

  def page_title(_, _opts) do
    "StampBot - AI YouTube Timestamp Generator"
  end
end
